spring:
  application:
    name: 2cmall-search
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.198:8848
  elasticsearch:
    rest:
      uris: http://192.168.0.198:9200
  thymeleaf:
    cache: false
server:
  port: 40000
logging:
  level:
    com.cambrian.mall: debug