spring:
  application:
    name: 2cmall-search
  cloud:
    nacos:
      discovery:
        server-addr: 2cmall.com:8848
  elasticsearch:
    rest:
      uris: http://2cmall.com:9200
  redis:
    host: 2cmall.com
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis
server:
  port: 40000
logging:
  level:
    com.cambrian.mall: debug