spring:
  application:
    name: 2cmall-search
  cloud:
    nacos:
      discovery:
        server-addr: 2cmall.com:8848
  elasticsearch:
    rest:
      uris: http://2cmall.com:9200
  thymeleaf:
    cache: false
server:
  port: 40000
logging:
  level:
    com.cambrian.mall: debug