spring:
  application:
    name: 2cmall-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://localhost:9200
server:
  port: 40000
