spring:
  application:
    name: 2cmall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 2cmall.com:8848
  redis:
    host: 2cmall.com
    port: 6379
  thymeleaf:
    cache: false
  session:
    store-type: redis
server:
  port: 41000
  servlet:
    session:
      timeout: 30m
logging:
  level:
    org.springframework.web.client: debug
