spring:
  application:
    name: 2cmall-third-party
  cloud:
    nacos:
      discovery:
        server-addr: 2cmall.com:8848
    alicloud:
      oss:
        bucket: 2cmall
server:
  port: 30000
mall:
  third:
    sms:
      host: http://wwww.baidu.com
      app-code: app-code
      method: POST
      sms-sign-id: xxxx
      template-id: 1234