spring:
  application:
    name: 2cmall-product
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/2cmall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 2cmall.com:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 2cmall.com
    port: 6379
  cache:
    type: REDIS
    redis:
      time-to-live: 1h
      cache-null-values: true
      use-key-prefix: true
  session:
    store-type: redis
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0

server:
  port: 10000

logging:
  level:
    com.cambrian.mall: debug
cmall:
  thread-pool:
    core-size: 20
    max-size: 200
    keep-alive-time: 10